---
title: "NEON_data_grab"
authors: Kade Stewart, 
output: html_document
date: "2026-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages to run script
```{r library}
library(tidyverse)
library(here)
library(neonUtilities)
```

Hey this is a test on 2/17/2026!

Pulling NEON Data 'Discharge' from BIGC, TECR 2/17
```{r}
#Pull data
discharge <- "DP4.00130.001"

#Select sites and dates *DATES SHOULD BE REEVALUATED
my_sites <- c("BIGC", "TECR", "REDB", "SYCA", "LECO", "WALK", "MAYF")
start_date <- "2018-11"
end_date <- "2022-12"

#Pull
list2env((loadByProduct(dpID = discharge, 
                        site = my_sites, 
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```
Saving raw data variables 
```{r}

#Save raw data DONE
variables_00130 %>% 
  write_csv(here("data", "raw", "variables_00130.csv"))

csd_15_min %>% 
  write_csv(here("data", "raw", "csd_15_min.csv"))

```
Pulling NEON Data 'Fish electrofishing, gill netting, and fyke netting counts' from BIGC, TECR.
```{r}
#Pull data from	"Fish electrofishing, gill netting, and fyke netting counts"
fish <- "DP1.20107.001"

#Select sites and dates 
my_sites <- c("BIGC", "TECR", "REDB", "SYCA", "LECO", "WALK", "MAYF")
start_date <- "2012-01"
end_date <- "2022-12"

#Pull
list2env((loadByProduct(dpID = fish, 
                        site = my_sites, 
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```
Saving raw data variables 
```{r}
#Save raw data DONE
variables_20107 %>% 
  write_csv(here("data", "raw", "variables_20107.csv"))

fsh_perFish %>% 
  write_csv(here("data", "raw", "fsh_perFish.csv"))

```
Pulling NEON Data 'Aquatic plants' from from BIGC, TECR.
```{r}
#Pull data from "Aquatic plants"
plants <- "DP1.20072.001"

#Select sites and dates
my_sites <- c("BIGC", "TECR", "REDB", "SYCA", "LECO", "WALK", "MAYF")
start_date <- "2012-01"
end_date <- "2022-12"

list2env((loadByProduct(dpID = plants, 
                        site = my_sites, 
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)   
```
Save raw variables 
```{r}
#Save raw data DONE
variables_20072 %>% 
  write_csv(here("data", "raw", "variables_20072.csv"))

apc_perTaxon %>% 
  write_csv(here("data", "raw", "apc_perTaxon.csv"))

```


```{r}
#Save raw data
variables_20086 %>% 
  write_csv(here("data", "raw", "variables_20086.csv"))

csd_15_min %>% 
  write_csv(here("data", "raw", "csd_15_min.csv"))
```