---
title: "NEON_data_cleanup"
output: html_document
date: "2026-02-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load in Tidyverse and Here library

```{r}
library(tidyverse)
library(here)
```
## read in the raw data for discharge and check structure 

```{r}
discharge_raw <- read_csv(here("data", "raw", "csd_15_min.csv"))

head(discharge_raw)
str(discharge_raw)
view(discharge_raw)
```

## select variables 

```{r}
discharge <- discharge_raw %>% 
  select(domainID,
         siteID,
         startDateTime,
         endDateTime,
         stageContinuous,
         stageTotalUncert,
         dischargeContinuous,
         dischargeUpperParamUncert,
         dischargeLowerParamUncert,
         dischargeUpperRemnUncert,
         dischargeLowerRemnUncert,
         dischargeCorrectionApplied,
         dischargeFinalQF,
         dischargeFinalQFSciRvw)
```

```{r}

discharge %>% 
  write_csv(here("data", "processed", "discharge_processed.csv"))

```


## Preliminary Plot
```{r}
ggplot(data = discharge,
       aes(x = startDateTime, 
           y = dischargeContinuous,
           col = siteID)) +
  geom_point(cex = 1) +
  stat_smooth()
```


You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
